[managers.system]
items = [
	"fzf",       # fuzzy finder
	"ncdu",      # file size inspector (like TreeSize)
	"exa",       # better ls
	"bat",       # better cat
	"ripgrep",   # cli file content seaercher
	"zoxide",    # better cd
	"mc",        # cli file manager
	"btop",      # cli system process monitor
	"tldr",      # the shorter manpage
	"thefuck",   # command autocorrector (command: 'fuck')
	"fastfetch", # neofetch alternative
]

[managers.cargo]
items = [
	"du-dust", # another file size inspector
]
