[managers.system]
items = [
	"nodejs", # javascript runtime
	"python3-pip",
]

[managers.pip]
items = [
	"toml", # toml package for python (used for alacritty assembler script)
	"pre-commit",	# pre-commit for checking secrets before git commit
]

[managers.npm-global]
items = [
	"bun",  # bun javascript package manager and runtime
	"yarn", # yarn javascript package manager
	"pnpm", # pnpm javascript package manager
]
