[managers.system]
items = [
	"nodejs", # javascript runtime
]

[managers.pip]
items = [
	"toml", # toml package for python (used for alacritty assembler script)
]

[managers.npm-global]
items = [
	"bun",  # bun javascript package manager and runtime
	"yarn", # yarn javascript package manager
	"pnpm", # pnpm javascript package manager
]
